### ISSUE TITLE
basic usage

### ISSUE THREAD

**Issue by superloach** [bspaans/bleep#3]
Hi there! I was interested in using this library for a game, but I wasn't sure where to start.

Is there an example anywhere of creating a simple sine instrument and sending note events to it?

**Comment by bspaans** [comment]
Hi, thanks for your issue. We're unfortunately a bit light on documentation, but the most basic way to generate notes is to use generators directly:

```cfg := audio.NewAudioConfig()
g := generators.NewSineWaveOscillator()
g.SetPitch(440.0)
g.GetSamples(cfg, 44000)```

As you mentioned note events the next step would be to assign the generator to a Channel, add the Channel to a Mixer, and the Mixer to a Synth. A Synth can read events from its Inputs channel so that will allow you to send NoteOns and NoteOffs, etc. Hope that helps.
